# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvZf3xd0Uf9UWG7ePqIKeAAGdCa4el5V
"""

cat > fire_yolo.py << 'ENDOFFILE'
from ultralytics import YOLO
import cv2
from datetime import datetime

# Model path
MODEL_PATH = "/home/orin/Downloads/Smoke Fire.pt"

print("🔥 Loading YOLO Fire Detection Model...")
model = YOLO(MODEL_PATH)

# Initialize webcam
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not cap.isOpened():
    print("❌ Error: Cannot open webcam")
    exit()

print("✅ System Ready!")
print("Press 'q' to quit, 's' to save screenshot\n")

conf_thresh = 0.25
imgsz = 640

cv2.namedWindow("Fire Detection - YOLO", cv2.WINDOW_NORMAL)
cv2.resizeWindow("Fire Detection - YOLO", 1280, 720)

frame_idx = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_idx += 1
    h, w = frame.shape[:2]

    # Convert to RGB for YOLO
    img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # Run YOLO inference
    results = model.predict(source=[img_rgb], imgsz=imgsz, conf=conf_thresh, verbose=False, save=False)
    r = results[0]

    fire_detected = False

    # Draw bounding boxes
    if r.boxes is not None and len(r.boxes) > 0:
        fire_detected = True
        for box in r.boxes:
            xyxy = box.xyxy.cpu().numpy().astype(int)[0]
            conf = float(box.conf.cpu().numpy()[0])
            cls = int(box.cls.cpu().numpy()[0]) if box.cls is not None else -1
            x1, y1, x2, y2 = xyxy

            # Get class name
            label = f"{model.names.get(cls, cls)} {conf:.2f}" if hasattr(model, "names") else f"{cls} {conf:.2f}"

            # Draw bounding box
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 255), 3)
            cv2.putText(frame, label, (x1, y1 - 10),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2, cv2.LINE_AA)

    # Draw segmentation masks if available
    if hasattr(r, "masks") and r.masks is not None:
        try:
            masks = r.masks.data.cpu().numpy()
            for m in masks:
                m_uint8 = (m * 255).astype('uint8')
                colored_mask = cv2.applyColorMap(m_uint8, cv2.COLORMAP_JET)
                alpha = 0.35
                colored_mask = cv2.resize(colored_mask, (w, h))
                mask_gray = cv2.resize(m_uint8, (w, h))
                mask_bool = mask_gray > 127
                frame[mask_bool] = cv2.addWeighted(frame, 1 - alpha, colored_mask, alpha, 0)[mask_bool]
        except Exception as e:
            pass

    # Display status
    if fire_detected:
        print(f"🚨 FIRE/SMOKE DETECTED at {datetime.now().strftime('%H:%M:%S')}")
        cv2.putText(frame, "STATUS: FIRE/SMOKE DETECTED!", (10, 30),
                   cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 3)
    else:
        cv2.putText(frame, "STATUS: Monitoring...", (10, 30),
                   cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

    # Show FPS
    cv2.putText(frame, f"Frame: {frame_idx}", (10, 60),
               cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

    cv2.imshow("Fire Detection - YOLO", frame)

    key = cv2.waitKey(1) & 0xFF
    if key == ord('q'):
        break
    elif key == ord('s'):
        cv2.imwrite(f"fire_yolo_{datetime.now().strftime('%H%M%S')}.jpg", frame)
        print("📸 Screenshot saved!")

cap.release()
cv2.destroyAllWindows()
print("System stopped")
ENDOFFILE
